<<<<<<< HEAD
spring.application.name=favouritePayee

# H2 DB config
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA config
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# VERY IMPORTANT
spring.jpa.defer-datasource-initialization=true

=======
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
>>>>>>> f91a8a85b4bb06532014c5b3945bbbba33b6f5a4
